# These are all the cops that are disabled in the default configuration.

Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Description: "Avoid chaining a method call on a do...end block."
  Enabled: false

Style/MultilineBlockChain:
  Description: "Avoid multi-line chains of blocks."
  Enabled: false

Style/BlockDelimiters:
  Description: >-
                Avoid using {...} for multi-line blocks (multiline chaining is
                always ugly).
                Prefer {...} over do...end for single-line blocks.
  Enabled: false

Style/SymbolArray:
  Description: "Use %i or %I for arrays of symbols."
  Enabled: false

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Description: "Use spaces inside hash literal braces - or don't."
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Description: "No space."
  Enabled: false

Rails/BulkChangeTable:
  Description: "No space."
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Description: "Keep blank lines around access modifiers."
  Enabled: false

Layout/AlignArguments:
  Description: "Align the arguments of a method call."
  Enabled: false

Style/EmptyLiteral:
  Description: "Prefer literals to Array.new/Hash.new/String.new."
  Enabled: false

Style/ClassAndModuleChildren:
  Description: "Checks style of children classes and modules."
  Enabled: false

Metrics/ClassLength:
  Description: "Avoid classes longer than 100 lines of code."
  Enabled: false

Metrics/ModuleLength:
  Description: "Avoid modules longer than 100 lines of code."
  Enabled: false

Layout/AlignHash:
  Description: "Align the elements of a hash literal if they span more than one line."
  Enabled: false

Metrics/MethodLength:
  Description: "Avoid methods longer than 10 lines of code."
  Enabled: false

Metrics/ParameterLists:
  Description: "Avoid parameter lists longer than three or four parameters."
  Enabled: false

Style/DoubleNegation:
  Description: "Checks for uses of double negation (!!)."
  Enabled: false

Metrics/CyclomaticComplexity:
  Description: "Avoid complex methods."
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/AlignArray:
  Description: >-
                 Align the elements of an array literal if they span more than
                 one line.
  Enabled: false

Style/UnneededPercentQ:
  Description: "Checks for %q/%Q when single quotes or double quotes would do."
  Enabled: false

Style/RescueModifier:
  Description: "Avoid using rescue in its modifier form."
  Enabled: false

Naming/AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

Style/Encoding:
  Description: "Use UTF-8 as the source file encoding."
  Enabled: false

Style/NestedParenthesizedCalls:
  Description: >-
                 Parenthesize method calls which are nested inside the
                 argument list of another parenthesized method call.
  Enabled: false

Style/ParallelAssignment:
  Description: "Do not use parallel assignment"
  Enabled: false

Style/ConditionalAssignment:
  Description: >-
                 Use the return value of `if` and `case` statements for
                 assignment to a variable and variable comparison instead
                 of assigning that variable inside of each branch.
  Enabled: false
  SingleLineConditionsOnly: false

Style/Lambda:
  Description: "Use the new lambda literal syntax for single-line blocks."
  Enabled: false

Style/StabbyLambdaParentheses:
  Description: 'Check for the usage of parentheses around stabby lambda arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#stabby-lambda-with-args'
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/RegexpLiteral:
  Description: >-
                 Use %r for regular expressions matching more than
                 `MaxSlashes` '/' characters.
                 Use %r only for regular expressions matching more than
                 `MaxSlashes` '/' character.
  Enabled: false

Style/FormatString:
  Description: 'Favor format over String#%'
  Enabled: false

#################### Lint ################################
### Warnings
Lint/AssignmentInCondition:
  Description: "Don't use assignment in conditions."
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Description: 'Shadowing outer local variable'
  Enabled: false

Style/RedundantSelf:
  Description: "Don't use self where it's not needed."
  Enabled: false

Rails/FindBy:
  Description: 'Prefer find_by over where.first.'
  Enabled: false

Rails/Output:
  Description: 'Do not write to stdout. Use Rails logger if you want to log.'
  Enabled: false

Style/BlockComments:
  Description: "Do not use block comments."
  Enabled: false

Rails/Date:
  Enabled: false
  Description: >-
                  Do not use to_time on Date objects, because they know
                  nothing about the time zone in use

Rails/TimeZone:
  Enabled: false
  Description: >-
                  Do not use Time.at without zone. Use one of Time.zone.at,
                  Time.current, Time.at.in_time_zone, Time.at.utc,
                  Time.at.getlocal, Time.at.iso8601, Time.at.jisx0301,
                  Time.at.rfc3339, Time.at.to_i, Time.at.to_f instead

Layout/EndAlignment:
  Description: "Align ends correctly."
  Enabled: false


Security/Open:
  Description: 'The use of `Kernel#open` is a serious security risk'
  Enabled: false

Layout/MultilineOperationIndentation:
    Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Rails/ActiveRecordAliases:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
